### ISSUE TITLE
All numbers in Addr are ints

### ISSUE THREAD

**Issue by matthieu** [blockcypher/gobcy#1]
For blockchains with large amounts (*cough* dogecoin *cough*) or very large or active wallets, total received, sent or balance can overflow an int. Someday, even NumTx could.

**Comment by acityinohio** [comment]
Ah good call. And also, _classic_ dogecoin. Wish there was an int128 type...I guess Big Int is the answer? https://golang.org/pkg/math/big/

**Comment by matthieu** [comment]
uint64 should be enough, faster and much easier to manipulate.

**Comment by acityinohio** [comment]
:+1: I'll probably keep a few things as ints (off the top of my head, unconfirmed_balance because negatives are possible and should never be very big)

**Comment by acityinohio** [comment]
JIC anyone is following this, @matthieu and I talked in meatspace and agreed that this came down to a 32-bit vs 64-bit issue (since [Go 1.1](https://golang.org/doc/go1.1#int) the size of the `int` type is based on the underlying architecture). For almost all cases, 64-bit ints should be fine (except in super weird/pathological cases and/or potentially dogecoin :dog:), and keeping the type as `int` reduces a fair amount of cognitive overhead. We're going to add specific warnings/suggestions for those who are on 32-bit systems in the README and godoc.
