### ISSUE TITLE
Use int64 instead of int for values

### ISSUE THREAD

**Issue by ThePiachu** [blockcypher/gobcy#5]
The package appears to use `int` to represent satoshi amounts in transactions. As in Go `int` [can be either](https://golang.org/ref/spec#Numeric_types) `int32` or `int64`, some people might run into problems by trying to spend more than 21.474'836'47 BTC. All `int`s relating to value should be converted to `int64` to avoid any issues.

**Comment by acityinohio** [comment]
Thanks for the feedback! We had this discussion a little while ago (https://github.com/blockcypher/gobcy/issues/1). Since Go 1.1, any 64-bit system defaults to making `int` 64-bit, so we opted for this warning in the readme instead:

https://github.com/blockcypher/gobcy#a-warning-for-32-bit-systems

It keeps the types a little cleaner, and most folks who are using the API through Go are doing so on 64-bit systems.
